language: node_js

node_js:
  - 7.5.0

cache:
  yarn: true
  directories:
    - node_modules

script: npm run build -- --prod

deploy:
  provider: firebase
  on: master
  skip_cleanup: true
  token:
    secure: "hEJMB4Ks0zYVbdDA1v9fAfOtY48pOu9MDa1v8QVBoHW/4Z2SlKuNguWASlpyfVZuBXQw8lDYwRVfyVVrZ33bYbHOY5HQGdICQc6Kp74Hm4ODZyJ21OqzFC6eLqiQEi0pXiFcNuM24QW2rF0xgXDWZLyAXStV6OSdYdQ33gN/0nu5ypAusWFdC2y6tehPcL9jVbBuQDQDbDJ3S2ifo8NaqdmKsCmKOE77oBXEEL1wA+mVwulGVqBhM1JwbAjReyrKvlCeWixmI8U8CTY7DgyWtJyYWwC9RFj0aOYObQ5ZPX5GPBKRvf5KhVes2E8P1cB2w9nJ8IwDHK3sq6ahwMH7QHJFQJwFEvG1c3UfzOUmLOEJjMNHYf0b98WRJPLIc/BHai/+HNCtU/imEKSNh6MZNmERf1d6jV/fTSP47846tasvqGuf+GQx3QYhsFGOkEhZkJmfA+WlTfXW56Ie+3XkS5e1m9xLYsF6zSK6Hpf62jwnl3Z1YTfg5uYb2wKj89o1+hCrkSYx/Mn9wBYyzHUeHlQHA8IdXkGX35QawkCg6Rg6HPqayJDH2zqQBioU1iXquTEjlBU3AZWHJvK5o15qDKrUxWvxM6JQYqAnrwjT32+dltz0+7/t9M+a1D5nyqTLl88B4+DHVzgLwufThJEw5RcBbGsNv8Fs9LJYH1m0VKU="